Editable poll answers (in wizard)
threema-ch/threema-android pull request #5
Opened 2021-03-12 18:50 UTC by oemel09

## Description

- Adds an edit button to answers when creating a poll
- Focuses the poll title edit text when the title was missing
- Removes the maxLines restriction for poll answers in the dialog. It's quite bad when you can't read the whole answer before the poll is closed. So I think even when the dialog may become quite big ans you have to scroll a lot, it's worth being able to read the whole answer.

One thing I was wondering about: is there a reason, why the `ExpandableTextEntryDialog` tries to get the callback activity or fragment automatically? I wasn't able to catch the callback inside the fragment. The Dialog tried to invoke the callback on the activity containing the fragment...
Also ` public void onAttach(@NonNull Activity activity)` which is used there is deprecated.

That's why I added the method `setCallback` to pass an `ExpandableTextEntryDialogClickListener` explicitly.

## Checklist

- [X] I signed the [Contributor License Agreement](https://threema.ch/en/open-source/cla)
- [X] All changes in this pull request were made by me, I own the full copyright
      for all these changes

2021-05-02 18:26 UTC, threema-maurus commented
@oemel09 Simply call `setTargetFragment(this, 0)` on the `ExpandableTextEntryDialog` instance to get the `onYes()` and `onNo()` callbacks in the fragment.
`public void onAttach(@NonNull Activity activity)` has apparently been deprecated in favor of `public void onAttach(@NonNull Context context)`in current `Fragment` implementations. We're eventually going to refactor this.

2021-05-05 14:50 UTC, oemel09 commented
Thanks @threema-maurus. I wasn't aware of the setTargetFragment method. I corrected it

2021-05-13 07:00 UTC, threema-maurus requested changes

2021-05-26 15:56 UTC, oemel09 commented on app/src/main/res/layout/item_ballot_choice_vote.xml
> -			android:maxLines="3"
This is the dialog item, which is only shown when voting, not when creating the ballot. So I think it makes sense to remove the `maxLines` restriction here.

2021-05-26 15:56 UTC, oemel09 commented on app/src/main/res/layout/item_ballot_wizard1.xml
> -			android:singleLine="true"/>
I'll add back the `singleLine` attribute here due to your argument from above

2021-05-26 15:59 UTC, oemel09 commented on app/src/main/res/layout/item_ballot_choice_vote.xml
> -			android:maxLines="3"
This is the layout which is used in the dialog when voting, not when creating a ballot.
I'll add back the singleLine attribute to the layout used when creating a poll.

2021-08-19 06:18 UTC, oemel09 commented
Will this PR be part of the next release? Or do I need to improve something else?

2021-08-19 07:19 UTC, threema-maurus commented
> Will this PR be part of the next release? Or do I need to improve something else?

@oemel09 Yes. This PR is already included in the latest series of betas for release 4.56. Thanks for contributing!

2021-08-19 07:19 UTC, closed without merging